### ISSUE TITLE
ikuuu机场无法签到，几鸡签到正常

### ISSUE THREAD

**Issue by x1737886903** [WindFgg/Scripts#10]
运行提示：
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /ql/scripts/jcCheck.js:96:23
    at /ql/scripts/jcCheck.js:174:6928
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by x1737886903** [comment]
无法正常运行，大佬，请问如何解决？
